export type StoreItemType = {
  id: string;
  myStoreImgSrc: string;
  myStoreSingleProductImgSrc: string;
  myStoreAlt: string;
  title: string;
  price: number;
  mainDescription: string;
  singleDescription: string;
  type: string;
  publisher: string;
  isAudio: boolean;
  isDVD: boolean;
  length: string;
  format: string;
  language: string;
  paperback: string;
  dimensions: string;
  isPositionedIcon: boolean;
  positionedIconSrc: string;
  positionedIconAlt: string;
};